// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/robot.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RobotTracker_TrackRobot_FullMethodName = "/robot.RobotTracker/TrackRobot"
)

// RobotTrackerClient is the client API for RobotTracker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RobotTrackerClient interface {
	// 用於發送機器人位置的流式 RPC
	TrackRobot(ctx context.Context, in *TrackRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Position], error)
}

type robotTrackerClient struct {
	cc grpc.ClientConnInterface
}

func NewRobotTrackerClient(cc grpc.ClientConnInterface) RobotTrackerClient {
	return &robotTrackerClient{cc}
}

func (c *robotTrackerClient) TrackRobot(ctx context.Context, in *TrackRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Position], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RobotTracker_ServiceDesc.Streams[0], RobotTracker_TrackRobot_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TrackRequest, Position]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RobotTracker_TrackRobotClient = grpc.ServerStreamingClient[Position]

// RobotTrackerServer is the server API for RobotTracker service.
// All implementations must embed UnimplementedRobotTrackerServer
// for forward compatibility.
type RobotTrackerServer interface {
	// 用於發送機器人位置的流式 RPC
	TrackRobot(*TrackRequest, grpc.ServerStreamingServer[Position]) error
	mustEmbedUnimplementedRobotTrackerServer()
}

// UnimplementedRobotTrackerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRobotTrackerServer struct{}

func (UnimplementedRobotTrackerServer) TrackRobot(*TrackRequest, grpc.ServerStreamingServer[Position]) error {
	return status.Errorf(codes.Unimplemented, "method TrackRobot not implemented")
}
func (UnimplementedRobotTrackerServer) mustEmbedUnimplementedRobotTrackerServer() {}
func (UnimplementedRobotTrackerServer) testEmbeddedByValue()                      {}

// UnsafeRobotTrackerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RobotTrackerServer will
// result in compilation errors.
type UnsafeRobotTrackerServer interface {
	mustEmbedUnimplementedRobotTrackerServer()
}

func RegisterRobotTrackerServer(s grpc.ServiceRegistrar, srv RobotTrackerServer) {
	// If the following call pancis, it indicates UnimplementedRobotTrackerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RobotTracker_ServiceDesc, srv)
}

func _RobotTracker_TrackRobot_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TrackRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RobotTrackerServer).TrackRobot(m, &grpc.GenericServerStream[TrackRequest, Position]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RobotTracker_TrackRobotServer = grpc.ServerStreamingServer[Position]

// RobotTracker_ServiceDesc is the grpc.ServiceDesc for RobotTracker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RobotTracker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "robot.RobotTracker",
	HandlerType: (*RobotTrackerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TrackRobot",
			Handler:       _RobotTracker_TrackRobot_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/robot.proto",
}
