// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/robot.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackRequest) Reset() {
	*x = TrackRequest{}
	mi := &file_proto_robot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackRequest) ProtoMessage() {}

func (x *TrackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_robot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackRequest.ProtoReflect.Descriptor instead.
func (*TrackRequest) Descriptor() ([]byte, []int) {
	return file_proto_robot_proto_rawDescGZIP(), []int{0}
}

type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_proto_robot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_proto_robot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_proto_robot_proto_rawDescGZIP(), []int{1}
}

func (x *Position) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Position) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Position) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_proto_robot_proto protoreflect.FileDescriptor

const file_proto_robot_proto_rawDesc = "" +
	"\n" +
	"\x11proto/robot.proto\x12\x05robot\"\x0e\n" +
	"\fTrackRequest\"D\n" +
	"\bPosition\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp2F\n" +
	"\fRobotTracker\x126\n" +
	"\n" +
	"TrackRobot\x12\x13.robot.TrackRequest\x1a\x0f.robot.Position\"\x000\x01B;Z9github.com/tetsufromtw/practice-robot/robot-tracker/protob\x06proto3"

var (
	file_proto_robot_proto_rawDescOnce sync.Once
	file_proto_robot_proto_rawDescData []byte
)

func file_proto_robot_proto_rawDescGZIP() []byte {
	file_proto_robot_proto_rawDescOnce.Do(func() {
		file_proto_robot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_robot_proto_rawDesc), len(file_proto_robot_proto_rawDesc)))
	})
	return file_proto_robot_proto_rawDescData
}

var file_proto_robot_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_robot_proto_goTypes = []any{
	(*TrackRequest)(nil), // 0: robot.TrackRequest
	(*Position)(nil),     // 1: robot.Position
}
var file_proto_robot_proto_depIdxs = []int32{
	0, // 0: robot.RobotTracker.TrackRobot:input_type -> robot.TrackRequest
	1, // 1: robot.RobotTracker.TrackRobot:output_type -> robot.Position
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_robot_proto_init() }
func file_proto_robot_proto_init() {
	if File_proto_robot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_robot_proto_rawDesc), len(file_proto_robot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_robot_proto_goTypes,
		DependencyIndexes: file_proto_robot_proto_depIdxs,
		MessageInfos:      file_proto_robot_proto_msgTypes,
	}.Build()
	File_proto_robot_proto = out.File
	file_proto_robot_proto_goTypes = nil
	file_proto_robot_proto_depIdxs = nil
}
