# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: robot.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'robot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0brobot.proto\x12\x05robot\"\x0e\n\x0cTrackRequest\"3\n\x08Position\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x32\x46\n\x0cRobotTracker\x12\x36\n\nTrackRobot\x12\x13.robot.TrackRequest\x1a\x0f.robot.Position\"\x00\x30\x01\x42;Z9github.com/tetsufromtw/practice-robot/robot-tracker/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z9github.com/tetsufromtw/practice-robot/robot-tracker/proto'
  _globals['_TRACKREQUEST']._serialized_start=22
  _globals['_TRACKREQUEST']._serialized_end=36
  _globals['_POSITION']._serialized_start=38
  _globals['_POSITION']._serialized_end=89
  _globals['_ROBOTTRACKER']._serialized_start=91
  _globals['_ROBOTTRACKER']._serialized_end=161
# @@protoc_insertion_point(module_scope)
